# Generated by Django 4.1.3 on 2023-04-18 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(default='user', max_length=20)),
                ('balance', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Accouts',
            },
        ),
    ]
