# Generated by Django 4.1.3 on 2023-04-25 15:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': 'Accounts'},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='current_money',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
