# Generated by Django 4.1.3 on 2023-05-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_alter_account_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100, unique=True)),
                ('finished', models.BooleanField(default=False)),
                ('goal_money', models.FloatField()),
                ('current_money', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Financial Goals',
            },
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100, unique=True)),
                ('finished', models.BooleanField(default=False)),
                ('goal_money', models.FloatField()),
                ('current_money', models.FloatField(default=0)),
                ('to_go_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Spendings',
            },
        ),
    ]
