# Generated by Django 4.1.3 on 2023-05-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_financialgoal_spending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='to_go_date',
            field=models.DateTimeField(verbose_name='%Y-%m-%d'),
        ),
    ]
